version: "3.4"
services:
  app:
    image: real-estate-api
    build:
      context: .
      dockerfile: ./Dockerfile.localdev
    ports:
      - "8800:8800"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: mongodb://admin:123123@localhost:27017/real_estate_db?authSource=admin&directConnection=true
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123123
      MONGO_INITDB_DATABASE: real_estate_db
    command: mongod --auth

volumes:
  mongo_data: